#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftBack,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     scissorFront,  tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     rightFront,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     ballRamp,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ballContainer,        tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabberRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabberLeft,        tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    grabberSide,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotFunctions.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
	servo[ballContainer] = 220;
	servo[grabberRight] = 180;
	return;
}

task main() {
	//Ball Grabber facing rolling goals from ramp
	initializeRobot();
	waitForStart();
	move(6.5 * 12, 65);
	grabRollingGoalLeft();
	wait1Msec(500);
	turn(23, 20, true);
	move(2.5 * 12, 75);
	grabRollingGoalRight();
	wait1Msec(1000);
	turn(40, 20, false);

	move(8 * 12, -75);
	turn(180, 20, true);
	releaseRollingGoalRight();
	releaseRollingGoalLeft();
}
