#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftBack,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     scissorFront,  tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftFront,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightBack,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     rightFront,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     ballRamp,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ballContainer,        tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabberRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabberLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    grabberSide,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotFunctions.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
	servo[ballContainer] = 220;
	servo[grabberRight] = 160;
	servo[grabberLeft] = 160;
	servo[grabberSide] = 160;
	return;
}

task main() {
	//Ball grabber facing towards your ramp
	initializeRobot();
	waitForStart();
	move(2 * 12, 75);
	turn(90, 40, false);
	move(1 * 12, 75);
	turn(90, 40, true);
	move(5 * 12, 75);
	turn(90, 40, false);
	move(14, 75);
	turn(45, 40, true);
	move(2, 75);
	wait1Msec(200);
	grabRollingGoalLeft();
	wait1Msec(200);
	turn(45, 40, false);
	move(4, -75);
	turn(90, 45, true);
	move(18, 75);
	wait1Msec(200);
	grabRollingGoalRight();
	wait1Msec(200);
	turn(22, 40, false);
	move(8 * 12, -75);
	turn(180, 60, true);
}
